### ISSUE TITLE
Include tabindex="-1" if it's the currently focussed element.

### ISSUE THREAD

**Issue by slafleche** [davidtheclark/tabbable#27]
When an element has `tabindex="-1` it's not tabbable, unless you use Javascript to set the focus. If an element with `tabindex="-1"` has focus, it would be nice to include it, at least with an option.

**Comment by davidtheclark** [comment]
> When an element has tabindex="-1 it's not tabbable

Yep, it's not tabbable. So I don't think it should be returned in an array of tabbable elements, which is the purpose of this library, right? Maybe this could be clarified if you'd elaborate on your use case?

**Comment by slafleche** [comment]
I'm using your library to help with web accessibility. My use case would be if you want to set the focus to another location, relative to an element with tabindex=-1. Other fields are dynamic, so I can't rely on a specific field. Knowing the relative location of that tabindex=-1 element to other tabbable elements helps to figure out where focus should go.

**Comment by davidtheclark** [comment]
@slafleche I think this might make more sense within your own code instead of in the library. Tabbable is not going to be able to know where to put your `tabindex="-1"` element within the ordered array it returns, because that element doesn't actually *belong* in the ordered array, right (because it's not part of the tab order)?

There are a variety of ways you might accomplish this. Two ideas come to mind that I might experiment with: you could create different tabbable arrays before and after your `tabindex="-1"` element; you could insert that element into the place you know it belongs in the array returned by tabbable.
